sudo: required
dist: trusty

language: cpp
compiler:
  - gcc
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install build-essential g++ clang-3.5 libglu1-mesa-dev zlib1g-dev libalure-dev libvorbisfile3 libvorbis-dev 
      libdumb1-dev libboost-all-dev libc++-dev libsfml-dev gcc-multilib g++-multilib libc6:i386 libncurses5:i386 
      libstdc++6:i386 lib32z1-dev libglu1-mesa:i386 libx11-6:i386
  
  # Ubuntu is a turd
  - sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so
  - sudo ln -s /usr/lib/i386-linux-gnu/libX11.so.6 /usr/lib/i386-linux-gnu/libX11.so
  - sudo ln -s /usr/lib/i386-linux-gnu/libGLU.so.1 /usr/lib/i386-linux-gnu/libGLU.so
  - sudo ln -s /usr/include/x86_64-linux-gnu/zconf.h /usr/include
  
install:
  - make
  - make emake

env:
  matrix:
  #BEGIN LINUX
    # Game Modes
    - COMPILER=gcc PLATFORM=xlib MODE=Run GRAPHICS=OpenGL1 AUDIO=None COLLISION=None NETWORK=None WIDGETS=None EXTENSIONS=""
    - COMPILER=gcc PLATFORM=xlib MODE=Debug GRAPHICS=OpenGL1 AUDIO=None COLLISION=None NETWORK=None WIDGETS=None EXTENSIONS=""
    - COMPILER=gcc PLATFORM=xlib MODE=Compile GRAPHICS=OpenGL1 AUDIO=None COLLISION=None NETWORK=None WIDGETS=None EXTENSIONS=""

script:
  - ./emake --mode Rebuild -o /tmp/test
  - ./emake --compiler $COMPILER --platform $PLATFORM --graphics $GRAPHICS --audio $AUDIO --collision $COLLISION
      --network $NETWORK --widgets $WIDGETS -o /tmp/test

