language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install g++ zlib1g-dev libglu1-mesa-dev libalure-dev libvorbisfile3 libvorbis-dev libdumb1-dev libboost-all-dev
install:
  - python install.py
script: 
  - make
  - make emake
  - ./emake -o /tmp/test
  - ./emake -o /tmp/test -g OpenGL3
